version: "3.7"

services:

  database:
    image: tinkerpop/gremlin-server:latest
    ports:
    - ${DB_PORT:-8182}

  aws:
    image: localstack/localstack:latest
    environment:
    - SERVICES=ses
    - DEBUG=${AWS_DEBUG:-false}

  app:
    image: zerobaseio/smart-tracing-api:${APP_VERSION:-latest}
    ports:
    - ${APP_PORT:-9000}
    depends_on:
    - database
    - aws
    environment:
    - WRITE_ENDPOINT=database
    - READ_ENDPOINT=database
    - DB_PORT=8182
    - AWS_SES_ENDPOINT=http://aws:4579
    - PORT=${APP_PORT:-9000}


