---
server:
  applicationConnectors:
  - type: http
    port: ${PORT:-9000}
logging:
  loggers:
    # Enable errors from body processing
    io.dropwziard.jersey.jackson.JsonProcessingExceptionMapper: DEBUG
database:
  hosts: ${DB_HOSTS}
  port: ${DB_PORT}

siteTypeCategories:
  BUSINESS:
    - GROCERY
    - RESTAURANT
  FINANCIAL:
    - BANK
  HEALTH:
    - DOCTOR_OFFICE
    - HOSPITAL
    - PHARMACY

scannableTypes:
  - QR_CODE
