---
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: ${PORT:-8080}
  requestLog:
    appenders:
    - type: console
      filterFactories:
      - type: noise
        path: healthcheck

allowedOrigins: ${CORS_ALLOWED_ORIGINS}

logging:
  level: ${ROOT_LOG_LEVEL:-INFO}
  appenders:
  - type: console
    layout:
      type: json
      flattenMdc: true
      timestampFormat: ISO_INSTANT
  loggers:
    io.zerobase: ${PROJECT_LOG_LEVEL:DEBUG}
    # Enable errors from body processing
    io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper: DEBUG

database:
  endpoints:
    write: ${WRITE_ENDPOINT}
    read: ${READ_ENDPOINT}
  port: ${DB_PORT}
  enableAwsSigner: ${ENABLE_AWS_SIGNING:-true}
  enableSsl: ${ENABLE_SSL:-true}

baseQrCodeLink: ${BASE_LINK}

aws:
  ses:
    region: ${AWS_SES_REGION:-us-east-1}
    endpoint: ${AWS_SES_ENDPOINT:-null}
  s3:
    region: ${AWS_S3_REGION:-us-east-1}
    endpoint: ${AWS_S3_ENDPOINT:-null}

notifications:
  staticResourcesBucket: ${STATIC_RESOURCES_BUCKET}
  email:
    fromAddress: ${EMAIL_NOTIFICATION_FROM_ADDRESS:-noreply@zerobase.io}

siteTypeCategories:
  BUSINESS:
  - GROCERY
  - RESTAURANT
  - OTHER
  FINANCIAL:
  - BANK
  - OTHER
  HEALTH:
  - DOCTOR_OFFICE
  - HOSPITAL
  - PHARMACY
  - OTHER
  OTHER:
  - OTHER

scannableTypes:
- QR_CODE
