---
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: ${PORT:-8080}
  requestLog:
    appenders:
    - type: console
      filterFactories:
      - type: noise
        path: healthcheck

logging:
  level: ${ROOT_LOG_LEVEL:-INFO}
  loggers:
    # Enable errors from body processing
    io.dropwziard.jersey.jackson.JsonProcessingExceptionMapper: DEBUG

database:
  endpoints:
    write: ${WRITE_ENDPOINT}
    read: ${READ_ENDPOINT}
  port: ${DB_PORT}
  enableAwsSigner: ${ENABLE_AWS_SIGNING:-true}
  enableSsl: ${ENABLE_SSL:-true}

amazonaws:
  ses:
    region: US_EAST_1

emailConfig:
  CREATE_ORG:
    subject: "Thank you joining our program"
    resource: "email-templates/org-join"
  CREATE_SCANNABLE:
    subject: "Thank you for creating a qr code"
    resource: "email-templates/create-qr-code"
    attach_name: "qr-code.pdf"
  CREATE_USER:
    subject: "Thank you for joining"
    resource: "email-templates/user-join"
  DELETE_USER:
    subject: "Sorry to see you go"
    resource: "email-templates/user-delete"

appConfig:
  fromEmail: ${FROM_EMAIL:-""}

siteTypeCategories:
  BUSINESS:
    - GROCERY
    - RESTAURANT
  FINANCIAL:
    - BANK
  HEALTH:
    - DOCTOR_OFFICE
    - HOSPITAL
    - PHARMACY

scannableTypes:
  - QR_CODE
