---
server:
  applicationConnectors:
  - type: http
    port: ${PORT:-9000}
database:
  url: ${GRAPHENEDB_BOLT_URL:-bolt://localhost:7474}
  username: ${GRAPHENEDB_BOLT_USER:-neo4j}
  password: ${GRAPHENEDB_BOLT_PASSWORD}
