---
server:
  applicationConnectors:
  - type: http
    port: ${PORT:-9000}

database:
  endpoints:
    write: localhost
  port: ${DB_PORT:-8182}

siteTypeCategories:
  BUSINESS:
    - GROCERY
    - RESTAURANT
  FINANCIAL:
    - BANK
  HEALTH:
    - DOCTOR_OFFICE
    - HOSPITAL
    - PHARMACY

scannableTypes:
  - QR_CODE
