---
server:
  applicationConnectors:
  - type: http
    port: ${PORT:-9000}

database:
  endpoints:
    write: ${DB_HOST:-localhost}
  port: ${DB_PORT:-8182}

aws:
  ses:
    region: ${REGION:-us-east-1}
    endpoint: ${FAKE_SES_ENDPOINT:-null}

notifications:
  email:
    fromAddress: ${NOTIFICATION_FROM_EMAIL_ADDRESS:-noreply@zerobase.io}

siteTypeCategories:
  BUSINESS:
    - GROCERY
    - RESTAURANT
  FINANCIAL:
    - BANK
  HEALTH:
    - DOCTOR_OFFICE
    - HOSPITAL
    - PHARMACY

scannableTypes:
  - QR_CODE
