---
server:
  applicationConnectors:
  - type: http
    port: ${PORT:-9000}

database:
  hosts: [localhost]

siteTypeCategories:
  BUSINESS:
    - GROCERY
    - RESTAURANT
  FINANCIAL:
    - BANK
  HEALTH:
    - DOCTOR_OFFICE
    - HOSPITAL
    - PHARMACY

scannableTypes:
  - QR_CODE
