name: Build and deploy to staging
on:
  push:
    branches:
    - master
    tag-ignore:
    - v*
    paths:
    - pom.xml
    - src/*

jobs:
  release:
    name: Release and deploy
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Perform Java Release
      run: |
        git config user.name=github-actions
        git config user.email=no-reply@zerobase.io
        mvn -B release:prepare release:perform -DscmCommentPrefix='[skip ci]' -DtagNameFormat='v@{project.version}' -DdeployAtEnd=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push docker image
      run: |
        version=$(cat target/classes/build.properties | grep version | awk -F= '{print $2}')
        docker build . -t zerobaseio/smart-tracing-api:${version} -t zerobaseio/smart-tracing-api:latest
        docker login --username zerboaseuser --password ${DOCKERHUB_ACCESS_TOKEN}
        docker push zerobaseio/smart-tracing-api
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Deploy to staging environment
      run: |
        pip install boto3
        version=$(cat target/classes/build.properties | grep version | awk -F= '{print $2}')
        cd cloudformation
        export AWS_DEFAULT_REGION=us-east-1
        python deploy.py api staging ${version}
